platform: linux

image_resource:
  type: docker-image
  source:
    repository: microsoft/dotnet

inputs:
- name: cf-sample-app-dotnetcore

run:
  path: sh
  args: ["cf-sample-app-dotnetcore/ci/build.sh"]
